#!/bin/bash
#KellyShyno
#customBash
#version: 2.2.1

number='^[0-9]+$';
chmod -R a+rx *;


banner()
{
clear;
sleep 0.16;
echo "";
echo -e '\e[1;36m                _                  ____            _\e[0m';
echo -e '\e[1;36m  ___ _   _ ___| |_ ___  _ __ ___ | __ )  __ _ ___| |__\e[0m';
echo -e '\e[1;35m / __| | | / __| __/ _ \| "_ " _ \|  _ \ / _" / __|  _ \\\e[0m';
echo -e '\e[1;35m| (__| |_| \__ \ || (_) | | | | | | |_) | (_| \__ \ | | |\e[0m';
echo -e '\e[1;36m \___|\__,_|___/\__\___/|_| |_| |_|____/ \__,_|___/_| |_|\e[0m';
echo "";
echo -e "\e[1;31mversion: 2.2.1\e[0m";
echo "";
}


error()
{
clear; echo -e "\e[1;31mERROR: write the correct sign..\e[0m"; sleep 0.6;
}


input()
{
echo "";
echo -en "\e[1;35m (\e[0m""\e[1;31m#\e[0m""\e[1;35m_\e[0m""\e[1;31m#\e[0m";
echo -en "\e[1;35m)\e[0m" "\e[1;31m> \e[0m";
}


inputYN()
{
echo "";
echo -en "\e[1;35m (\e[0m""\e[1;31mo\e[0m""\e[1;35m_\e[0m""\e[1;31mO\e[0m";
echo -en "\e[1;35m) \e[0m";
echo -en "\e[1;35m[\e[0m""\e[1;31my\e[0m""\e[1;35m/\e[0m""\e[1;31mn\e[0m";
echo -en "\e[1;35m]\e[0m" "\e[1;31m> \e[0m";
}


backOrExit()
{
echo -e "\e[1;30mTo back: \"b\" | To exit: \"x\"\e[0m";
echo "";
}


back()
{
echo "";
echo -e "\e[1;33m====================================\e[0m";
echo -en '\e[1;33m|  \e[0m'"\e[1;31m[ \e[0m""\e[1;36mb\e[0m""\e[1;31m ] \e[0m";
echo -en "\e[1;36mback\e[0m"'\e[1;33m  ||  ';
echo -en "\e[1;35m[ \e[0m""\e[1;36md\e[0m""\e[1;35m ] \e[0m";
echo -e "\e[1;36mdownload\e[0m"'\e[1;33m  |';
echo -e "\e[1;33m====================================\e[0m";
}


color()
{
echo "";
echo -e "\e[1;35m/ \e[0m""\e[1;36m1\e[0m""\e[1;35m / \e[0m""\e[1;37mwhite\e[0m";
echo -e "\e[1;35m/ \e[0m""\e[1;36m2\e[0m""\e[1;35m / \e[0m""\e[1;30mgrey\e[0m";
echo -e "\e[1;35m/ \e[0m""\e[1;36m3\e[0m""\e[1;35m / \e[0m""\e[1;36mcyan\e[0m";
echo -e "\e[1;35m/ \e[0m""\e[1;36m4\e[0m""\e[1;35m / \e[0m""\e[1;35mpurple\e[0m";
echo -e "\e[1;35m/ \e[0m""\e[1;36m5\e[0m""\e[1;35m / \e[0m""\e[1;31mred\e[0m";
echo -e "\e[1;35m/ \e[0m""\e[1;36m6\e[0m""\e[1;35m / \e[0m""\e[1;33myellow\e[0m";
echo -e "\e[1;35m/ \e[0m""\e[1;36m7\e[0m""\e[1;35m / \e[0m""\e[1;32mgreen\e[0m";
echo -e "\e[1;35m/ \e[0m""\e[1;36m8\e[0m""\e[1;35m / \e[0m""\e[1;34mblue\e[0m";
}


aboutUs()
{
banner;
backOrExit;
echo -en "\e[1;36m⊹ \e[0m";
echo -e "\e[1;35mProgram:\e[0m" "\e[1;4;36mcustomBash\e[0m";
echo -en "\e[1;36m⊹ \e[0m";
echo -e "\e[1;35mAuthor:\e[0m" "\e[1;4;36mKellyShyno\e[0m";
echo -en "\e[1;36m⊹ \e[0m";
echo -e "\e[1;35mVk:\e[0m" "\e[1;4;36mhttps://vk.com/linuxkelly\e[0m";
echo "";
back;
input;
  read backAboutUs
    case $backAboutUs in
"b") shyno; ;;
"x") echo ""; exit 0; ;;
*) error; aboutUs; ;;
    esac;
}


colorHandling()
{
    case $colorBlock in
1) colorBlock="\\\e[1;37m$block\\\e[0m"; ;;
2) colorBlock="\\\e[1;30m$block\\\e[0m"; ;;
3) colorBlock="\\\e[1;36m$block\\\e[0m"; ;;
4) colorBlock="\\\e[1;35m$block\\\e[0m"; ;;
5) colorBlock="\\\e[1;31m$block\\\e[0m"; ;;
6) colorBlock="\\\e[1;33m$block\\\e[0m"; ;;
7) colorBlock="\\\e[1;32m$block\\\e[0m"; ;;
8) colorBlock="\\\e[1;34m$block\\\e[0m"; ;;
*) colorBlock=""; ;;
    esac;
}


theEnd()
{
banner;
echo -e "\e[1;32mComplete\e[0m";

  case $endText in
"nothing") echo -en "\e[1;35mYou set nothing..\e[0m"; ;;
*) echo -en "\e[1;36mOpen new shell to see changes..\e[0m"; ;;
  esac;

echo -en "\e[1;35m(\e[0m""\e[1;31m#\e[0m""\e[1;35m_\e[0m""\e[1;31m#\e[0m";
echo -e "\e[1;35m)\e[0m";
echo "";
echo -en "\e[1;30mpress any key: \e[0m";
 read end
    case $end in
"") shyno; ;;
*) shyno; ;;
    esac;
}


backupConfig()
{
#TODO
echo
}


bashCheckModule()
{
  if [[ $timeValue == "n" ]]; then
    if [[ $userValue == "n" ]]; then
      sed -i "s/.*PS1.*/PS1=\'$customAdditionColor\\\w\\\\$ \'/" /data/data/com.termux/files/usr/etc/bash.bashrc;
    else
      sed -i "s/.*PS1.*/PS1=\'$userColor $customAdditionColor\\\w\\\\$ \'/" /data/data/com.termux/files/usr/etc/bash.bashrc;
    fi;
  else
    sed -i "s/.*PS1.*/PS1=\'$timeColor $userColor $customAdditionColor\\\w\\\\$ \'/" /data/data/com.termux/files/usr/etc/bash.bashrc;
  fi;
}


installing()
{
#backup
backupConfig;

#custom bash
#processing
colorBlock=$timeColor; block="\\\@"; colorHandling; timeColor=$colorBlock
colorBlock=$userColor; block="\\\u"; colorHandling; userColor=$colorBlock
colorBlock=$customAdditionColor; block="\\$customAdditionText";
colorHandling; customAdditionColor=$colorBlock;

#installing custom bash
if [[ $timeValue == "n" && $userValue == "n" && $customAdditionValue == "n" && $motdValue == "n" ]]; then
 endText="nothing";
elif [[ $timeValue == "n" && $userValue == "n" && $customAdditionValue == "n" ]]; then
 echo;
else
 bashCheckModule;
fi;

#custom motd
  case $motdValue in
"y") echo "" > /data/data/com.termux/files/usr/etc/motd;
echo "$motdText" >> /data/data/com.termux/files/usr/etc/motd;
echo "" >> /data/data/com.termux/files/usr/etc/motd;
echo "" >> /data/data/com.termux/files/usr/etc/motd;
theEnd; ;;
*) theEnd; ;;
  esac;
}


returnOrContinue()
{
banner;
backOrExit;
echo -e "\e[1;36mContinue or return?\e[0m";
echo "";
echo -e "\e[1;35m/ \e[0m""\e[1;36m1\e[0m""\e[1;35m / \e[0m""\e[1;36mcontinue\e[0m";
echo -e "\e[1;35m/ \e[0m""\e[1;36m2\e[0m""\e[1;35m / \e[0m""\e[1;36mreturn\e[0m";
input;
 read retCont
    case $retCont in
1) installing; ;;
2) timeDisplay; ;;
"b") motdDisplay; ;;
"x") echo ""; exit 0; ;;
*) error; returnOrContinue; ;;
  esac;
}


motdText()
{
banner;
backOrExit;
echo -e "\e[1;36mEnter the text for custom motd\e[0m";
input;
 read motdText
    case $motdText in
"b") motdDisplay; ;;
"x") echo ""; exit 0; ;;
"") error; motdText; ;;
*) returnOrContinue; ;;
  esac;
}


motdDisplay()
{
banner;
backOrExit;
echo -e "\e[1;36mDo install the custom motd?\e[0m";
inputYN;
 read motdValue
    case $motdValue in
"y") motdText; ;;
"n") returnOrContinue; ;;
"b") customAdditionDisplay; ;;
"x") echo ""; exit 0; ;;
*) error; motdDisplay; ;;
    esac;
}


customAdditionColor()
{
banner;
backOrExit;
echo -e "\e[1;36mWhat color will be installed for custom addition?\e[0m";
color;
input;
 read customAdditionColor
    case $customAdditionColor in
1) motdDisplay; ;;
2) motdDisplay; ;;
3) motdDisplay; ;;
4) motdDisplay; ;;
5) motdDisplay; ;;
6) motdDisplay; ;;
7) motdDisplay; ;;
8) motdDisplay; ;;
"b") customAdditionText; ;;
"x") echo ""; exit 0; ;;
*) error; customAdditionColor; ;;
    esac;
}


userColor()
{
banner;
backOrExit;
echo -e "\e[1;36mWhat color will be installed for user?\e[0m";
color;
input;
 read userColor
    case $userColor in
1) customAdditionDisplay; ;;
2) customAdditionDisplay; ;;
3) customAdditionDisplay; ;;
4) customAdditionDisplay; ;;
5) customAdditionDisplay; ;;
6) customAdditionDisplay; ;;
7) customAdditionDisplay; ;;
8) customAdditionDisplay; ;;
"b") userDisplay; ;;
"x") echo ""; exit 0; ;;
*) error; userColor; ;;
    esac;
}


timeColor()
{
banner;
backOrExit;
echo -e "\e[1;36mWhat color will be installed for time?\e[0m";
color;
input;
 read timeColor
    case $timeColor in
1) userDisplay; ;;
2) userDisplay; ;;
3) userDisplay; ;;
4) userDisplay; ;;
5) userDisplay; ;;
6) userDisplay; ;;
7) userDisplay; ;;
8) userDisplay; ;;
"b") timeDisplay; ;;
"x") echo ""; exit 0; ;;
*) error; timeColor; ;;
    esac;
}


customAdditionText()
{
banner;
backOrExit;
echo -en "\e[1;36mEnter the text for custom addition \e[0m";
echo -e "\e[1;31m(prohibited only numbers)\e[0m";
input;
 read customAdditionText

  if [[ $customAdditionText == "b" ]]; then
customAdditionDisplay;
  elif [[ $customAdditionText == "x" ]]; then
echo ""; exit 0;
  elif [[ $customAdditionText == "" ]]; then
error; customAdditionText;
  elif [[ $customAdditionText =~ $number ]]; then
error; customAdditionText;
  else
customAdditionColor;
  fi;
}


customAdditionDisplay()
{
banner;
backOrExit;
echo -e "\e[1;36mDo install the custom addition?\e[0m";
inputYN;
 read customAdditionValue
  case $customAdditionValue in
"y") customAdditionText; ;;
"n") motdDisplay; ;;
"b") userDisplay; ;;
"x") echo ""; exit 0; ;;
*) error; customAdditionDisplay; ;;
  esac;
}


userDisplay()
{
banner;
backOrExit;
echo -e "\e[1;36mDo install display of the user?\e[0m";
inputYN;
 read userValue
  case $userValue in
"y") userColor; ;;
"n") customAdditionDisplay; ;;
"b") timeDisplay; ;;
"x") echo ""; exit 0; ;;
*) error; userDisplay; ;;
  esac;
}


timeDisplay()
{
banner;
backOrExit;
echo -e "\e[1;36mDo install display of the time?\e[0m";
inputYN;
 read timeValue
  case $timeValue in
"y") timeColor; ;;
"n") userDisplay; ;;
"b") shyno; ;;
"x") echo ""; exit 0; ;;
*) error; timeDisplay; ;;
  esac;
}


returnBash()
{
banner;
echo -e "\e[1;35msoon..\e[0m";
echo "";
echo -en "\e[1;30mpress any key: \e[0m";
 read returnBash
    case $returnBash in
"") shyno; ;;
*) shyno; ;;
    esac;
}


returnMotd()
{
banner;
echo -e "\e[1;35msoon..\e[0m";
echo "";
echo -en "\e[1;30mpress any key: \e[0m";
 read returnMotd
    case $returmMotd in
"") shyno; ;;
*) shyno; ;;
    esac;
}


patternBash()
{
banner;
echo -e "\e[1;35msoon..\e[0m";
echo "";
echo -en "\e[1;30mpress any key: \e[0m";
 read patternBash
    case $patternBash in
"") shyno; ;;
*) shyno; ;;
    esac;
}


shyno()
{
banner;
echo -e "\e[1;35m/ \e[0m""\e[1;36m1\e[0m""\e[1;35m / \e[0m""\e[1;36mcreate bash\e[0m";
echo -e "\e[1;35m/ \e[0m""\e[1;36m2\e[0m""\e[1;35m / \e[0m""\e[1;36mbash pattern\e[0m";
echo -e "\e[1;35m/ \e[0m""\e[1;36m3\e[0m""\e[1;35m / \e[0m""\e[1;36mreturn bash\e[0m";
echo -e "\e[1;35m/ \e[0m""\e[1;36m4\e[0m""\e[1;35m / \e[0m""\e[1;36mreturn motd\e[0m";
echo -e "\e[1;35m/ \e[0m""\e[1;36m5\e[0m""\e[1;35m / \e[0m""\e[1;36mabout us\e[0m";
echo -e "\e[1;35m/ \e[0m""\e[1;31mu\e[0m""\e[1;35m / \e[0m""\e[1;35mupdate\e[0m";
echo -e "\e[1;35m/ \e[0m""\e[1;31mx\e[0m""\e[1;35m / \e[0m""\e[1;31mexit\e[0m";
input;
 read shy
    case $shy in
1) timeDisplay; ;;
2) patternBash; ;;
3) returnBash; ;;
4) returnMotd; ;;
5) aboutUs; ;;
"u") ./data/update/update.sh; shyno; ;;
"x") echo ""; exit 0; ;;
*) error; shyno; ;;
    esac;
}


checkTermuxOrLinux()
{
  if [[ -d /data/data/com.termux/files/home ]]; then
shyno;
  else
banner;
echo -e "\e[1;35mIt's not termux :(\e[0m";
echo "";
echo -en "\e[1;30mpress any key: \e[0m";
 read checkTermuxOrLinux
    case $checkTermuxOrLinux in
"") echo ""; exit 0; ;;
*) echo ""; exit 0; ;;
    esac;
  fi;
}
checkTermuxOrLinux;
